Repository wecode-bootcamp-korea/24-westagram-backend, pull requests merged in 2021-08, with the labels that each got.

#5 [서동규] Mission 1 : Django 초기 세팅
  students/donggyu/.gitignore
  students/donggyu/manage.py
  students/donggyu/requirements.txt
  students/donggyu/westagram/__init__.py
  students/donggyu/westagram/asgi.py
  students/donggyu/westagram/settings.py
  students/donggyu/westagram/urls.py
  students/donggyu/westagram/wsgi.py
Labels: Status: Accepted

#4 [김동준] Mission 1 : Django 초기세팅
  students/dongjunKim/.gitignore
  students/dongjunKim/manage.py
  students/dongjunKim/requirements.txt
  students/dongjunKim/westagram/__init__.py
  students/dongjunKim/westagram/asgi.py
  students/dongjunKim/westagram/settings.py
  students/dongjunKim/westagram/urls.py
  students/dongjunKim/westagram/wsgi.py
Labels: Status: Accepted

#7 [고영수] Mission 1: Django 초기 세팅
  students/youngsoo/.gitignore
  students/youngsoo/manage.py
  students/youngsoo/requirements.txt
  students/youngsoo/westagram/__init__.py
  students/youngsoo/westagram/asgi.py
  students/youngsoo/westagram/settings.py
  students/youngsoo/westagram/urls.py
  students/youngsoo/westagram/wsgi.py
Labels: Status: Accepted

#6 [서동규] Mission2: 모델링
  students/donggyu/users/__init__.py
  students/donggyu/users/admin.py
  students/donggyu/users/apps.py
  students/donggyu/users/migrations/0001_initial.py
  students/donggyu/users/migrations/__init__.py
  students/donggyu/users/models.py
  students/donggyu/users/tests.py
  students/donggyu/users/views.py
  students/donggyu/westagram/settings.py
Labels: Status: Accepted

#9 [성우진] Mission 1 : Django 초기 세팅
  students/woojin/.gitignore
  students/woojin/manage.py
  students/woojin/requirements.txt
  students/woojin/westagram/__init__.py
  students/woojin/westagram/asgi.py
  students/woojin/westagram/settings.py
  students/woojin/westagram/urls.py
  students/woojin/westagram/wsgi.py
Labels: Status: Accepted

#11 [김장호] Mission 1: Django 초기 세팅
  students/jangho/westagram/.gitignore
  students/jangho/westagram/manage.py
  students/jangho/westagram/requirements.txt
  students/jangho/westagram/westagram/__init__.py
  students/jangho/westagram/westagram/asgi.py
  students/jangho/westagram/westagram/settings.py
  students/jangho/westagram/westagram/urls.py
  students/jangho/westagram/westagram/wsgi.py
Labels: Status: Accepted

#12 [김정수]Mission 1: Django 초기 세팅
  students/jungsoo/.gitignore
  students/jungsoo/manage.py
  students/jungsoo/requirements.txt
  students/jungsoo/westagram/__init__.py
  students/jungsoo/westagram/asgi.py
  students/jungsoo/westagram/settings.py
  students/jungsoo/westagram/urls.py
  students/jungsoo/westagram/wsgi.py
Labels: Status: Accepted

#13 [이무현]Mission 1: Django 초기 세팅
  students/muhyun/.gitignore
  students/muhyun/manage.py
  students/muhyun/requirements.txt
  students/muhyun/westagram/__init__.py
  students/muhyun/westagram/asgi.py
  students/muhyun/westagram/settings.py
  students/muhyun/westagram/urls.py
  students/muhyun/westagram/wsgi.py
Labels: Status: 리뷰 요청

#15 [고준영] Mission 1: Django 초기 세팅
  students/joonyoung/.gitignore
  students/joonyoung/.vscode/settings.json
  students/joonyoung/config/__init__.py
  students/joonyoung/config/asgi.py
  students/joonyoung/config/settings.py
  students/joonyoung/config/urls.py
  students/joonyoung/config/wsgi.py
  students/joonyoung/manage.py
  students/joonyoung/requirements.txt
Labels: Status: 리뷰 요청

#16 [신우주] Mission 1: Django 초기 세팅
  students/wooju/.gitignore
  students/wooju/manage.py
  students/wooju/requirments.txt
  students/wooju/westagram/__init__.py
  students/wooju/westagram/asgi.py
  students/wooju/westagram/settings.py
  students/wooju/westagram/urls.py
  students/wooju/westagram/wsgi.py
Labels: Status: 리뷰 요청

#17 [최현수]Mission 1: Django 초기 세팅
  students/hyunsu/westagram/.gitignore
  students/hyunsu/westagram/manage.py
  students/hyunsu/westagram/requirements.txt
  students/hyunsu/westagram/westagram/__init__.py
  students/hyunsu/westagram/westagram/asgi.py
  students/hyunsu/westagram/westagram/settings.py
  students/hyunsu/westagram/westagram/urls.py
  students/hyunsu/westagram/westagram/wsgi.py
Labels: Status: 리뷰 요청

#19 [윤현묵] Mission 1 : Django 초기 세팅
  students/hyeonmuk/.gitignore
  students/hyeonmuk/manage.py
  students/hyeonmuk/requirements.txt
  students/hyeonmuk/westagram/__init__.py
  students/hyeonmuk/westagram/asgi.py
  students/hyeonmuk/westagram/settings.py
  students/hyeonmuk/westagram/urls.py
  students/hyeonmuk/westagram/wsgi.py
Labels: Status: 리뷰 요청

#20 [주종민] Mission 1 : Django 초기 세팅
  students/jongmin/.gitignore
  students/jongmin/manage.py
  students/jongmin/requirements.txt
  students/jongmin/westagram/__init__.py
  students/jongmin/westagram/asgi.py
  students/jongmin/westagram/settings.py
  students/jongmin/westagram/urls.py
  students/jongmin/westagram/wsgi.py
Labels: Status: 리뷰 요청

#22 [송치헌] Mission 1: Django 초기 세팅
  students/chiheon/westargram/manage.py
  students/chiheon/westargram/requirements.txt
  students/chiheon/westargram/westargram/.gitignore
  students/chiheon/westargram/westargram/__init__.py
  students/chiheon/westargram/westargram/asgi.py
  students/chiheon/westargram/westargram/settings.py
  students/chiheon/westargram/westargram/urls.py
  students/chiheon/westargram/westargram/wsgi.py
Labels: Status: 리뷰 요청

#23 [박지원] Mission 1: Django 초기 세팅
  students/jiwon/westagram/.gitignore
  students/jiwon/westagram/manage.py
  students/jiwon/westagram/requirements.txt
  students/jiwon/westagram/westagram/__init__.py
  students/jiwon/westagram/westagram/asgi.py
  students/jiwon/westagram/westagram/settings.py
  students/jiwon/westagram/westagram/urls.py
  students/jiwon/westagram/westagram/wsgi.py
Labels: Status: 리뷰 요청

#24 [하예준] Mission 1 : Django 초기 세팅
  students/yejun/.gitignore
  students/yejun/manage.py
  students/yejun/requirements.txt
  students/yejun/westagram/__init__.py
  students/yejun/westagram/asgi.py
  students/yejun/westagram/settings.py
  students/yejun/westagram/urls.py
  students/yejun/westagram/wsgi.py
Labels: Status: 리뷰 요청

#18 [고영수] Mission 2: 모델링
  students/youngsoo/users/__init__.py
  students/youngsoo/users/admin.py
  students/youngsoo/users/apps.py
  students/youngsoo/users/migrations/0001_initial.py
  students/youngsoo/users/migrations/__init__.py
  students/youngsoo/users/models.py
  students/youngsoo/users/tests.py
  students/youngsoo/users/views.py
  students/youngsoo/westagram/settings.py
Labels: Status: Accepted

#21 [성우진] Mission 2 : 모델링
  students/woojin/users/__init__.py
  students/woojin/users/admin.py
  students/woojin/users/apps.py
  students/woojin/users/migrations/__init__.py
  students/woojin/users/models.py
  students/woojin/users/tests.py
  students/woojin/users/views.py
Labels: Status: 리뷰 요청

#29 [윤현묵] Mission 2: 모델링
  students/hyeonmuk/hyeonmuk/__init__.py
  students/hyeonmuk/hyeonmuk/admin.py
  students/hyeonmuk/hyeonmuk/apps.py
  students/hyeonmuk/hyeonmuk/migrations/__init__.py
  students/hyeonmuk/hyeonmuk/models.py
  students/hyeonmuk/hyeonmuk/tests.py
  students/hyeonmuk/hyeonmuk/views.py
Labels: Status: 리뷰 요청

#26 [최현수] Mission 2: 모델링
  students/hyunsu/westagram/users/__init__.py
  students/hyunsu/westagram/users/admin.py
  students/hyunsu/westagram/users/apps.py
  students/hyunsu/westagram/users/migrations/__init__.py
  students/hyunsu/westagram/users/models.py
  students/hyunsu/westagram/users/tests.py
  students/hyunsu/westagram/users/views.py
  students/hyunsu/westagram/westagram/settings.py
Labels: Status: 리뷰 요청

#27 [송치헌] Mission 2: 모델링
  students/chiheon/westargram/users/__init__.py
  students/chiheon/westargram/users/admin.py
  students/chiheon/westargram/users/apps.py
  students/chiheon/westargram/users/migrations/0001_initial.py
  students/chiheon/westargram/users/migrations/__init__.py
  students/chiheon/westargram/users/models.py
  students/chiheon/westargram/users/tests.py
  students/chiheon/westargram/users/validation.py
  students/chiheon/westargram/users/views.py
  students/chiheon/westargram/westargram/settings.py
Labels: Status: 리뷰 요청

#28 [신우주] Mission 2: 모델링
  students/wooju/wooju/__init__.py
  students/wooju/wooju/admin.py
  students/wooju/wooju/apps.py
  students/wooju/wooju/migrations/__init__.py
  students/wooju/wooju/models.py
  students/wooju/wooju/tests.py
  students/wooju/wooju/views.py
Labels: Status: 리뷰 요청

#30 [박지원] Mission 2: 모델링
  students/jiwon/westagram/users/__init__.py
  students/jiwon/westagram/users/admin.py
  students/jiwon/westagram/users/apps.py
  students/jiwon/westagram/users/migrations/__init__.py
  students/jiwon/westagram/users/models.py
  students/jiwon/westagram/users/tests.py
  students/jiwon/westagram/users/views.py
Labels: Status: 리뷰 요청

#31 [하예준] Mission 2: 모델링
  students/yejun/.gitignore
  students/yejun/users/__init__.py
  students/yejun/users/admin.py
  students/yejun/users/apps.py
  students/yejun/users/migrations/0001_initial.py
  students/yejun/users/migrations/__init__.py
  students/yejun/users/models.py
  students/yejun/users/tests.py
  students/yejun/users/views.py
  students/yejun/westagram/settings.py
Labels: Status: 리뷰 요청

#25 [김동준] Mission 2 : 모델링
  students/dongjunKim/users/__init__.py
  students/dongjunKim/users/admin.py
  students/dongjunKim/users/apps.py
  students/dongjunKim/users/migrations/__init__.py
  students/dongjunKim/users/models.py
  students/dongjunKim/users/tests.py
  students/dongjunKim/users/views.py
  students/dongjunKim/westagram/settings.py
Labels: Status: 리뷰 요청

#32 [김장호] Mission 2: 모델링
  students/jangho/westagram/ecryptor.py
  students/jangho/westagram/users/__init__.py
  students/jangho/westagram/users/admin.py
  students/jangho/westagram/users/apps.py
  students/jangho/westagram/users/migrations/0001_initial.py
  students/jangho/westagram/users/migrations/0002_auto_20210821_1250.py
  students/jangho/westagram/users/migrations/__init__.py
  students/jangho/westagram/users/models.py
  students/jangho/westagram/users/tests.py
  students/jangho/westagram/users/views.py
  students/jangho/westagram/westagram/settings.py
Labels: Status: 리뷰 요청

#35 [이무현] Mission 2: 모델링
  students/muhyun/users/__init__.py
  students/muhyun/users/admin.py
  students/muhyun/users/apps.py
  students/muhyun/users/migrations/0001_initial.py
  students/muhyun/users/migrations/__init__.py
  students/muhyun/users/models.py
  students/muhyun/users/tests.py
  students/muhyun/users/views.py
  students/muhyun/westagram/settings.py
Labels: Status: 리뷰 요청

#10 [서동규] Mission3: 회원가입 기능 구현
  students/donggyu/users/urls.py
  students/donggyu/users/views.py
  students/donggyu/westagram/urls.py
Labels: Status: 리뷰 요청

#14 [손명희] Mission 2: 모델링
  students/myeonghee/users/__init__.py
  students/myeonghee/users/admin.py
  students/myeonghee/users/apps.py
  students/myeonghee/users/migrations/0001_initial.py
  students/myeonghee/users/migrations/0002_user.py
  students/myeonghee/users/migrations/__init__.py
  students/myeonghee/users/models.py
  students/myeonghee/users/tests.py
  students/myeonghee/users/urls.py
  students/myeonghee/users/views.py
  students/myeonghee/westagram/settings.py
  students/myeonghee/westagram/urls.py
Labels: Status: 리뷰 요청

#44 [고준영] Mission2 : 모델링
  students/joonyoung/.vscode/settings.json
  students/joonyoung/config/settings.py
  students/joonyoung/config/urls.py
  students/joonyoung/users/__init__.py
  students/joonyoung/users/admin.py
  students/joonyoung/users/apps.py
  students/joonyoung/users/migrations/__init__.py
  students/joonyoung/users/models.py
  students/joonyoung/users/tests.py
  students/joonyoung/users/urls.py
  students/joonyoung/users/views.py
Labels: Status: 리뷰 요청

#45 [김정수] Mission 2:모델링
  students/jungsoo/users/__init__.py
  students/jungsoo/users/admin.py
  students/jungsoo/users/apps.py
  students/jungsoo/users/migrations/0001_initial.py
  students/jungsoo/users/migrations/__init__.py
  students/jungsoo/users/models.py
  students/jungsoo/users/tests.py
  students/jungsoo/users/views.py
  students/jungsoo/westagram/settings.py
Labels: Status: 리뷰 요청

#39 [주종민] Mission 2: 모델링
  students/jongmin/users/__init__.py
  students/jongmin/users/admin.py
  students/jongmin/users/apps.py
  students/jongmin/users/migrations/__init__.py
  students/jongmin/users/models.py
  students/jongmin/users/tests.py
  students/jongmin/users/views.py
Labels: Status: 수정 요청

#37 [송치헌] Mission 3: 회원가입 기능 구현
  students/chiheon/westargram/users/urls.py
  students/chiheon/westargram/users/validation.py
  students/chiheon/westargram/users/views.py
  students/chiheon/westargram/westargram/urls.py
Labels: Status: 리뷰 요청

#36 [고영수] Mission 3: 회원가입 기능 구현
  students/youngsoo/users/migrations/0002_rename_phone_num_user_phone_number.py
  students/youngsoo/users/migrations/0003_alter_user_email.py
  students/youngsoo/users/models.py
  students/youngsoo/users/urls.py
  students/youngsoo/users/views.py
  students/youngsoo/westagram/urls.py
Labels: Status: 리뷰 요청

#38 [최현수] Mission 3: 회원가입 기능 구현
  students/hyunsu/westagram/users/migrations/0001_initial.py
  students/hyunsu/westagram/users/models.py
  students/hyunsu/westagram/users/urls.py
  students/hyunsu/westagram/users/views.py
  students/hyunsu/westagram/westagram/urls.py
Labels: Status: 리뷰 요청

#48 [고준영] Mission3 : 회원가입 기능 구현
  students/joonyoung/config/urls.py
  students/joonyoung/users/migrations/0001_initial.py
  students/joonyoung/users/urls.py
  students/joonyoung/users/views.py
Labels: Status: 리뷰 요청

#33 [김동준] Mission 3: 회원가입 기능 구현
  students/dongjunKim/users/views.py
  students/dongjunKim/westagram/settings.py
  students/dongjunKim/westagram/urls.py
Labels: Status: 리뷰 요청

#43 [서동규] Mission 4: 로그인 기능 구현
  students/donggyu/users/urls.py
  students/donggyu/users/views.py
Labels: Status: 리뷰 요청

#49 [하예준] Mission 3: 회원가입 기능 구현
  students/yejun/users/migrations/0002_rename_user_name_user_name.py
  students/yejun/users/urls.py
  students/yejun/users/views.py
  students/yejun/westagram/urls.py
Labels: Status: 리뷰 요청

#51 [고준영] Mission4 : 로그인 기능 구현
  students/joonyoung/users/urls.py
  students/joonyoung/users/views.py
Labels: Status: 리뷰 요청

#52 [성우진] Mission 3: 회원가입 기능 구현
  students/woojin/users/apps 2.py
  students/woojin/users/migrations/0001_initial.py
  students/woojin/users/tests 2.py
  students/woojin/users/urls.py
  students/woojin/users/views.py
  students/woojin/westagram/settings.py
  students/woojin/westagram/urls.py
Labels: Status: 리뷰 요청

#61 [하예준] Mission 4: 로그인 기능 구현
  students/yejun/users/urls.py
  students/yejun/users/views.py
Labels: Status: 리뷰 요청

#40 [윤현묵] Mission 3: 회원가입 기능 구현
  students/hyeonmuk/hyeonmuk/views.py
  students/hyeonmuk/users/__init__.py
  students/hyeonmuk/users/admin.py
  students/hyeonmuk/users/apps.py
  students/hyeonmuk/users/migrations/0001_initial.py
  students/hyeonmuk/users/migrations/__init__.py
  students/hyeonmuk/users/models.py
  students/hyeonmuk/users/tests.py
  students/hyeonmuk/users/urls.py
  students/hyeonmuk/users/views.py
  students/hyeonmuk/westagram/settings.py
  students/hyeonmuk/westagram/urls.py
Labels: Status: 리뷰 요청

#53 [서동규] Mission 5: 회원가입 비밀번호 암호화 적용
  students/donggyu/requirements.txt
  students/donggyu/users/views.py
  students/donggyu/westagram/settings.py
Labels: Status: 리뷰 요청

#47 [신우주] Mission 3: 회원가입 기능 구현
  students/wooju/users/__init__.py
  students/wooju/users/admin.py
  students/wooju/users/apps.py
  students/wooju/users/migrations/0001_initial.py
  students/wooju/users/migrations/__init__.py
  students/wooju/users/models.py
  students/wooju/users/tests.py
  students/wooju/users/urls.py
  students/wooju/users/views.py
  students/wooju/westagram/settings.py
  students/wooju/westagram/urls.py
  students/wooju/wooju/views.py
Labels: Status: 리뷰 요청

#54 [고준영] Mission 5: 회원가입 비밀번호 암호화 적용
  students/joonyoung/users/views.py
Labels: Status: 리뷰 요청

#59 [최현수] Mission 4: 로그인 기능 구현
  students/hyunsu/westagram/users/urls.py
  students/hyunsu/westagram/users/views.py
  students/hyunsu/westagram/westagram/urls.py
Labels: Status: 수정 요청

#56 [송치헌] Mission 4: 로그인 기능 구현
  students/chiheon/westargram/users/urls.py
  students/chiheon/westargram/users/views.py
Labels: Status: 리뷰 요청

#65 [신우주] Mission 4: 로그인 기능 구현
  students/wooju/users/urls.py
  students/wooju/users/views.py
Labels: Status: Accepted

#46 [손명희] Mission 3: 회원가입 기능 구현
  students/myeonghee/users/urls.py
  students/myeonghee/users/views.py
  students/myeonghee/westagram/urls.py
Labels: Status: 리뷰 요청

#64 [주종민] Misson 3: 회원가입 기능구현
  students/jongmin/users/migrations/0001_initial.py
  students/jongmin/users/migrations/0002_alter_user_phone_number.py
  students/jongmin/users/models.py
  students/jongmin/users/urls.py
  students/jongmin/users/views.py
  students/jongmin/westagram/settings.py
  students/jongmin/westagram/urls.py
Labels: Status: 리뷰 요청

#68 [윤현묵] Mission 4: 로그인 기능 구현
  students/hyeonmuk/users/urls.py
  students/hyeonmuk/users/views.py
Labels: Status: Accepted

#69 [하예준] Mission 5: 회원가입 비밀번호 암호화 적용
  students/yejun/users/views.py
Labels: Status: 리뷰 요청

#58 [김정수] Mission 3: 회원가입 기능 구현
  students/jungsoo/users/urls.py
  students/jungsoo/users/views.py
  students/jungsoo/westagram/urls.py
Labels: Status: 리뷰 요청

#62 [성우진] Mission 4: 로그인 기능 구현
  students/woojin/users/urls.py
  students/woojin/users/views.py
Labels: Status: 리뷰 요청

#66 [서동규] Mission 6: 로그인 JWT 적용
  students/donggyu/users/views.py
  students/donggyu/westagram/settings.py
Labels: Status: 리뷰 요청

#67 [고준영] Mission 6: 로그인 JWT 적용
  students/joonyoung/users/migrations/0002_alter_user_password.py
  students/joonyoung/users/models.py
  students/joonyoung/users/views.py
Labels: Status: 리뷰 요청

#63 [박지원] Mission 3: 회원가입 기능 구현
  students/jiwon/westagram/users/migrations/0001_initial.py
  students/jiwon/westagram/users/models.py
  students/jiwon/westagram/users/urls.py
  students/jiwon/westagram/users/views.py
  students/jiwon/westagram/westagram/settings.py
  students/jiwon/westagram/westagram/urls.py
Labels: Status: 리뷰 요청

#50 [고영수] Mission 4: 로그인 기능 구현
  students/youngsoo/users/urls.py
  students/youngsoo/users/views.py
Labels: Status: 리뷰 요청

#70 [주종민] Misson 4: 로그인 기능구현
  students/jongmin/users/urls.py
  students/jongmin/users/views.py
Labels: Status: 리뷰 요청

#72 [김동준] Mission 4: 로그인 기능 구현
  students/dongjunKim/users/views.py
  students/dongjunKim/westagram/urls.py
Labels: Status: 리뷰 요청

#77 [이무현] Mission 4: 로그인 기능 구현
  students/muhyun/users/migrations/0003_alter_user_password.py
  students/muhyun/users/models.py
  students/muhyun/users/urls.py
  students/muhyun/users/views.py
Labels: Status: 수정 요청

#60 [손명희] Mission 4: 로그인 기능 구현
  students/myeonghee/users/models.py
  students/myeonghee/users/urls.py
  students/myeonghee/users/views.py
Labels: Status: conflict 해결 요청

#73 [성우진] Mission 5: 회원가입 비밀번호 암호화 적용
  students/woojin/users/views.py
Labels: Status: 리뷰 요청

#74 [최현수] Mission 5: 회원가입 비밀번호 암호화 적용
  students/hyunsu/westagram/users/migrations/0002_alter_user_password.py
  students/hyunsu/westagram/users/models.py
  students/hyunsu/westagram/users/views.py
Labels: Status: 리뷰 요청

#76 [송치헌] Mission 5: 회원가입 비밀번호 암호화 적용
  students/chiheon/westargram/users/views.py
Labels: Status: 리뷰 요청

#78 [신우주] Mission 5 회원가입 비밀번호 암호화 적용
  students/wooju/users/migrations/0002_alter_user_password.py
  students/wooju/users/models.py
  students/wooju/users/views.py
Labels: Status: 리뷰 요청

#75 [하예준] Mission 6 : 로그인 JWT 적용
  students/yejun/users/views.py
Labels: Status: 리뷰 요청

#79 [손명희] Mission 5: 회원가입 비밀번호 암호화 적용
  students/myeonghee/users/apps.py
  students/myeonghee/users/migrations/0001_initial.py
  students/myeonghee/users/migrations/0002_user.py
  students/myeonghee/users/models.py
  students/myeonghee/users/views.py
Labels: Status: 리뷰 요청

#80 [윤현묵] Mission 5: 회원가입 비밀번호 암호화 적용
  students/hyeonmuk/users/migrations/0002_alter_user_password.py
  students/hyeonmuk/users/migrations/0003_alter_user_password.py
  students/hyeonmuk/users/models.py
  students/hyeonmuk/users/urls.py
  students/hyeonmuk/users/views.py
Labels: Status: 리뷰 요청

#83 [고영수] Mission 5: 회원가입 비밀번호 암호화 적용
  students/youngsoo/users/migrations/0004_alter_user_password.py
  students/youngsoo/users/models.py
  students/youngsoo/users/views.py
Labels: Status: 리뷰 요청

#84 [김정수] Mission 5: 회원가입 비밀번호 암호화 적용
  students/jungsoo/users/migrations/0001_initial.py
  students/jungsoo/users/models.py
  students/jungsoo/users/views.py
Labels: Status: 리뷰 요청

#85 [이무현] Mission 5: 회원가입 비밀번호 암호화 적용
  students/muhyun/users/views.py
Labels: Status: 리뷰 요청

#87 [박지원] Mission 4: 로그인 기능 구현
  students/jiwon/westagram/users/urls.py
  students/jiwon/westagram/users/views.py
Labels: Status: 리뷰 요청

#55 [김장호] Mission 3: 회원가입 기능 구현
  students/jangho/westagram/requirements.txt
  students/jangho/westagram/users/migrations/0003_auto_20210823_0916.py
  students/jangho/westagram/users/migrations/0004_alter_user_phone.py
  students/jangho/westagram/users/models.py
  students/jangho/westagram/users/urls.py
  students/jangho/westagram/users/validation.py
  students/jangho/westagram/users/views.py
  students/jangho/westagram/westagram/urls.py
Labels: Status: 수정 요청

#99 [박지원] Mission 5: 회원가입 비밀번호 암호화 적용
  students/jiwon/westagram/users/migrations/0002_alter_user_password.py
  students/jiwon/westagram/users/models.py
  students/jiwon/westagram/users/views.py
Labels: Status: 리뷰 요청

#86 [송치헌] Mission 6: 로그인 JWT 적용
  students/chiheon/westargram/users/views.py
Labels: Status: 리뷰 요청

#89 [최현수] Mission 6: 로그인 JWT 적용
  students/hyunsu/westagram/users/views.py
Labels: Status: 리뷰 요청

#93 [이무현] Mission 6: 로그인 JWT 적용
  students/muhyun/users/views.py
Labels: Status: 리뷰 요청

#100 [신우주] Mission 6: 로그인 JWT 적용
  students/wooju/users/views.py
Labels: Status: 리뷰 요청

#90 [손명희] Mission 6: 로그인 JWT 적용
  students/myeonghee/users/utils.py
  students/myeonghee/users/views.py
Labels: Status: 리뷰 요청

#94 [김정수] mission 6: 로그인 JWT 적용
  students/jungsoo/postings/__init__.py
  students/jungsoo/postings/admin.py
  students/jungsoo/postings/apps.py
  students/jungsoo/postings/migrations/0001_initial.py
  students/jungsoo/postings/migrations/__init__.py
  students/jungsoo/postings/models.py
  students/jungsoo/postings/tests.py
  students/jungsoo/postings/views.py
  students/jungsoo/users/views.py
  students/jungsoo/westagram/settings.py
Labels: Status: 리뷰 요청

#95 [고영수] Mission 6: 로그인 JWT 적용
  students/youngsoo/users/views.py
Labels: Status: 리뷰 요청

#92 [성우진] Mission 6: 로그인 JWT 적용
  students/woojin/users/views.py
Labels: Status: 리뷰 요청

#104 [송치헌] Mission 6: 로그인 JWT 적용
  students/chiheon/westargram/postings/__init__.py
  students/chiheon/westargram/postings/admin.py
  students/chiheon/westargram/postings/apps.py
  students/chiheon/westargram/postings/migrations/0001_initial.py
  students/chiheon/westargram/postings/migrations/0002_alter_posting_post_time.py
  students/chiheon/westargram/postings/migrations/__init__.py
  students/chiheon/westargram/postings/models.py
  students/chiheon/westargram/postings/tests.py
  students/chiheon/westargram/postings/urls.py
  students/chiheon/westargram/postings/views.py
Labels: Status: 리뷰 요청, merge요청

#103 [주종민] Misson 6: 로그인JWT 구현
  students/jongmin/users/views.py
  students/jongmin/westagram/settings.py
Labels: Status: 리뷰 요청
